any_it = input('Digite algo: ')

print('O tipo primitivo desse valor é {}? '.format(type(any_it)))
print('Só tem espaços? {}'.format(any_it.isspace()))
print('É um número? {}'.format(any_it.isnumeric()))
print('É alfabético? {}'.format(any_it.isalpha()))
print('É alfanumérico? {}'.format(any_it.isalnum()))
print('Está em maiúsculas? {}'.format(any_it.isupper()))
print('Está em minúsculas? {}'.format(any_it.islower()))
print('Está capitalizada? {}'.format(any_it.istitle()))
