numero_tabuada = int(input('Digite um número para ver sua tabuada: '))
print('-' * 12)
print('{} x {:2} = {}'.format(numero_tabuada, 1, (numero_tabuada * 1)))
print('{} x {:2} = {}'.format(numero_tabuada, 2, (numero_tabuada * 2)))
print('{} x {:2} = {}'.format(numero_tabuada, 3, (numero_tabuada * 3)))
print('{} x {:2} = {}'.format(numero_tabuada, 4, (numero_tabuada * 4)))
print('{} x {:2} = {}'.format(numero_tabuada, 5, (numero_tabuada * 5)))
print('{} x {:2} = {}'.format(numero_tabuada, 6, (numero_tabuada * 6)))
print('{} x {:2} = {}'.format(numero_tabuada, 7, (numero_tabuada * 7)))
print('{} x {:2} = {}'.format(numero_tabuada, 8, (numero_tabuada * 8)))
print('{} x {:2} = {}'.format(numero_tabuada, 9, (numero_tabuada * 9)))
print('{} x {:2} = {}'.format(numero_tabuada, 10, (numero_tabuada * 10)))
print('-' * 12)